//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fax_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBfax : DbContext
    {
        public DBfax()
            : base("name=DBfax")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<main_class> main_class { get; set; }
        public virtual DbSet<person> people { get; set; }
        public virtual DbSet<rank> ranks { get; set; }
        public virtual DbSet<sub_class> sub_class { get; set; }
        public virtual DbSet<fax> faxes { get; set; }
        public virtual DbSet<iamge> iamges { get; set; }
    }
}
