//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fax_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fax
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fax()
        {
            this.iamges = new HashSet<iamge>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string name_send { get; set; }
        public string name_recieve { get; set; }
        public Nullable<System.DateTime> from_date { get; set; }
        public Nullable<System.DateTime> to_date { get; set; }
        public Nullable<int> serial_fax { get; set; }
        public int serial_fax_auto { get; set; }
        public Nullable<int> sub_class_id { get; set; }
        public Nullable<int> person_send_id { get; set; }
        public Nullable<int> person_recieve_id { get; set; }
        public Nullable<bool> is_export { get; set; }
    
        public virtual person person { get; set; }
        public virtual person person1 { get; set; }
        public virtual sub_class sub_class { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<iamge> iamges { get; set; }
    }
}
